site_name: 'TB-Profiler'
docs_dir: '../../docs/en'                         
site_dir: '../../build/en'                    

repo_url: https://github.com/jodyphelan/TBProfiler

markdown_extensions:
  - abbr
  - admonition
  - pymdownx.details
  - pymdownx.superfences
theme:
  name: material
  language: en
  
extra:
  alternate:
    - name: English
      link: https://jodyphelan.github.io/TBProfiler/en/
      lang: en
    - name: PortuguÃªs
      link: https://jodyphelan.github.io/TBProfiler/pt/
      lang: pt